import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
    weight: ['300', '400', '500', '700'], // Specify desired weights
    subsets: ['latin'], // Specify required subsets for language support
    display: 'swap', // Control font loading behavior
    variable: '--font-montserrat', // Define CSS variable for easy styling
  });


export const metadata: Metadata = {
  title: "Not a web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
